#!/bin/bash
cd /home/pi/tflite1 #&& mvn exec:exec &
source tflite1-env/bin/activate #&& mvn exec:exec &
python3 TFLite_detection_webcam.py --modeldir=Sample_TFLite_model --edgetpu && mvn exec:exec &

#python3 TFLite_detection_stream.py --modeldir=TFLite_model --streamurl="192.168.2.250:554/cam/realmonitor?channel=1&subtype=0" && mvn exec:exec &
#rtsp://admin:utsa1234@192.168.2.250:554/cam/realmonitor?channel=1&subtype=0